
  
jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
        gremlin_server: 3.4.0
      beta:
        rustup_toolchain: beta
        gremlin_server: 3.4.0
      nightly:
        rustup_toolchain: nightly
        gremlin_server: 3.4.0 
  steps:
  - ${{ if ne(parameters.name, 'Windows') }}:
    # Linux and macOS.
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install rust
  - ${{ if eq(parameters.name, 'Windows') }}:
    # Windows.
    - script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
      displayName: Install rust (windows)
  # All platforms.
  - script: |
        rustc -Vv
        cargo -V
  - script: rustup component add rustfmt
    displayName: Install Rustfmt 
  - script: cargo fmt --all -- --check
    displayName: Run Rustfmt 
  - script: rustup component add clippy
    displayName: Install Clippy
    condition: ne( variables['RUSTUP_TOOLCHAIN'], 'nightly' )
  - script: cargo clippy --all
    displayName: Run clippy
    condition: ne( variables['RUSTUP_TOOLCHAIN'] , 'nightly' )      
  - script: docker-compose -f docker-compose/docker-compose.yaml up -d 
    displayName: Run Grmelin Server
  - script: cargo test --all
    displayName: Cargo test   
  